version: '3'

services:
  api:
    container_name: sample_api
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile
    command: /bin/sh -c "rm -f /api/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/api:cached
      - bundle_cache:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    container_name: sample_db
    build:
      context: .
      dockerfile: ./.docker/db/Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sample_app
      POSTGRES_PASSWORD: sample_app_password
      POSTGRES_DB: sample_app_development

volumes:
  postgres-data:
  bundle_cache:
